### ISSUE TITLE
Downloaded music does not play on cellular data

### ISSUE THREAD

**Issue by mr-f0xx** [AppleBetas/Melody#29] opened 2017-06-03 15:28 UTC
It needs a Wifi connection to play music even if it's already in my iphone library
And no playing view when i play a track..

**Comment by AppleBetas** [comment] 2017-06-03 15:35
Now playing view is intentionally left out.

**Comment by AppleBetas** [comment] 2017-06-03 15:36
Cannot reproduce.

**Comment by AppleBetas** [comment] 2017-06-03 15:37
Was able to reproduce. Fixing soon.

**Comment by AppleBetas** [comment] 2017-06-03 16:02
Fixed in c032c7f

**Closed as completed by AppleBetas** 2017-06-03 16:02 UTC
Labels: bug
